### ISSUE TITLE
libnixstore: replace init function with a global once_cell static

### ISSUE THREAD

**Issue by MaeIsBad** [helsinki-systems/harmonia#23]
I think it would be more ergonomic and idiomatic to instead of requiring the user to explicitly call `libnixstore::init` replace it with something like

```rs
pub struct NixStore(());
pub static NIX_STORE: Lazy<NixStore> = Lazy::new(|| {
	libnixstore::init();
	NixStore(())
});

impl NixStore {
	pub fn is_valid_path(&self, path: &str) -> bool {
		libnixstore::is_valid_path(path)
	}
	// ... etc
}
```

**Comment by Conni2461** [comment]
Sorry for the somewhat late response and thanks for looking into the crate we wrote.

we already lazy initialize the nix store on cpp side as a `static shared_ptr` https://github.com/helsinki-systems/harmonia/blob/bd9119170866b030ab7123f11d50ad5ef1d3c56b/libnixstore/src/nix.cpp#L26-L33 which makes `::init` already optional. The docs i've written dont really state this fact which makes that definitely an issue, that should be addressed.

There are two reasons why i decided to provide an optional `init` function.
- First we try to mimic the already existing perl bindings and these provide a init function https://github.com/NixOS/nix/blob/7918adbb628e7781cec1638c371f2009136be68a/perl/lib/Nix/Store.xs#L48
- Second it allows devs to perform the work of `loadConfFile` and `openStore` on startup of the application rather than on while processing the first request. This could also be achieved by just logging the store path, which then initializes the store but i thought it wouldn't hurt.
